brew 'vim'
brew 'zsh'
brew 'zsh-completions'
brew 'tmux'
brew 'git'
brew 'stow'
brew 'leiningen'

tap 'caskroom/cask'
cask 'calibre'
cask 'docker'
cask 'firefox'
cask 'font-open-sans'
cask 'java' unless system '/usr/libexec/java_home --failfast'
cask 'screenhero'
cask 'skype'
cask 'spotify'
cask 'vagrant'
cask 'virtualbox'
cask 'xquartz'
