"$schema" = "https://starship.rs/config-schema.json"

add_newline = true

[hostname]
ssh_only = false
format = "[$hostname]($style) "
style = "bold dimmed green"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
truncation_length = 4
truncate_to_repo = true

[git_branch]
symbol = " "

[git_status]
ahead = "⇡${count}"
behind = "⇣${count}"
diverged = "⇕⇡${ahead_count}⇣${behind_count}"
staged = "[+${count}](green)"
modified = "[!${count}](yellow)"
untracked = "[?${count}](blue)"
deleted = "[-${count}](red)"

[nodejs]
symbol = " "

[python]
symbol = " "

[rust]
symbol = " "

[golang]
symbol = " "

[java]
symbol = " "

[package]
disabled = true
