#!/bin/bash
# scripts/prepare.sh
# Interactive pre-flight checklist for fresh machine onboarding

DOTFILES_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"

# Colors & Formatting
BOLD="\033[1m"
GREEN="\033[32m"
YELLOW="\033[33m"
RED="\033[31m"
CYAN="\033[36m"
RESET="\033[0m"

CRITICAL_ISSUES=()
ACTION_ITEMS=()

is_interactive() {
    [ -t 0 ]
}

prompt_confirm() {
    local prompt_msg="$1"
    local default_resp="${2:-Y}"
    local answer=""

    if is_interactive; then
        read -r -p "$prompt_msg " answer
    else
        echo "$prompt_msg (non-interactive: using $default_resp)"
        answer="$default_resp"
    fi

    if [ -z "$answer" ]; then
        answer="$default_resp"
    fi

    case "$answer" in
        [yY][eE][sS]|[yY]) return 0 ;;
        *) return 1 ;;
    esac
}

echo -e "${BOLD}=====================================================${RESET}"
echo -e "${BOLD}       DOTFILES ONBOARDING PRE-FLIGHT CHECK          ${RESET}"
echo -e "${BOLD}=====================================================${RESET}"

# 1. Xcode Command Line Tools
echo -e "\n${BOLD}[1/6] Checking Xcode Command Line Tools...${RESET}"
if xcode-select -p >/dev/null 2>&1; then
    CLT_PATH=$(xcode-select -p 2>/dev/null)
    echo -e "  ${GREEN}✅ Installed:${RESET} ${CLT_PATH}"
else
    echo -e "  ${RED}❌ Xcode Command Line Tools not found.${RESET}"
    if is_interactive && prompt_confirm "     Run 'xcode-select --install' now? [Y/n]"; then
        xcode-select --install 2>/dev/null || true
        echo -e "     ${YELLOW}⚠️ Complete the installation dialog before running 'make setup'.${RESET}"
    fi
    CRITICAL_ISSUES+=("Xcode Command Line Tools missing (run 'xcode-select --install')")
fi

# 2. Sudo privileges
echo -e "\n${BOLD}[2/6] Checking sudo privileges...${RESET}"
if is_interactive; then
    echo "  Requesting sudo credentials to cache authentication..."
    if sudo -v; then
        echo -e "  ${GREEN}✅ Sudo privileges verified and cached.${RESET}"
    else
        echo -e "  ${RED}❌ Failed to acquire sudo privileges.${RESET}"
        CRITICAL_ISSUES+=("Sudo privileges required for system configuration")
    fi
else
    if sudo -n -v >/dev/null 2>&1; then
        echo -e "  ${GREEN}✅ Sudo privileges verified (cached credentials).${RESET}"
    else
        echo -e "  ${YELLOW}⚠️ Sudo credentials not cached (non-interactive mode).${RESET}"
        echo -e "     Run 'sudo -v' before running 'make setup'."
        ACTION_ITEMS+=("Run 'sudo -v' to authenticate administrator privileges")
    fi
fi

# 3. Mac App Store login reminder
echo -e "\n${BOLD}[3/6] Checking Mac App Store status...${RESET}"
if command -v mas >/dev/null 2>&1; then
    MAS_ACCOUNT=$(mas account 2>/dev/null || true)
    if [ -n "$MAS_ACCOUNT" ]; then
        echo -e "  ${GREEN}✅ Signed into Mac App Store as:${RESET} ${MAS_ACCOUNT}"
    else
        echo -e "  ${YELLOW}⚠️ Not signed into the Mac App Store.${RESET}"
        echo -e "     Please open the App Store app and sign in."
        echo -e "     Brewfile requires login for: Xcode, Magnet, The Unarchiver."
        ACTION_ITEMS+=("Sign into Mac App Store for 'mas' apps (Xcode, Magnet, The Unarchiver)")
    fi
else
    echo -e "  ${CYAN}ℹ️ Mac App Store Reminder:${RESET}"
    echo -e "     Ensure you are signed into the Mac App Store app."
    echo -e "     Brewfile includes 'mas' apps: Xcode, Magnet, The Unarchiver."
    echo -e "     (Note: 'brew bundle' will fail if not signed into the App Store)"
fi

# 4. GPG key presence (key A37F13909665B893)
echo -e "\n${BOLD}[4/6] Checking GPG signing key...${RESET}"
GPG_KEY_ID="A37F13909665B893"
GPG_FOUND=false

if command -v gpg >/dev/null 2>&1; then
    if gpg --list-secret-keys "$GPG_KEY_ID" >/dev/null 2>&1; then
        GPG_FOUND=true
    fi
fi

if [ "$GPG_FOUND" = true ]; then
    echo -e "  ${GREEN}✅ GPG secret key ${GPG_KEY_ID} found in keyring.${RESET}"
else
    echo -e "  ${YELLOW}⚠️ GPG signing key ${GPG_KEY_ID} not found in keyring.${RESET}"
    if [ -f "$HOME/.gitconfig.local" ]; then
        echo -e "  ${GREEN}ℹ️ ~/.gitconfig.local already exists.${RESET}"
    else
        echo -e "     Global git config enforces commit signing by default."
        echo -e "     Without your key or ~/.gitconfig.local, git commits will fail."
        if is_interactive && prompt_confirm "     Generate ~/.gitconfig.local with [commit] gpgsign = false? [Y/n]"; then
            cat << 'EOF_LOCAL' > "$HOME/.gitconfig.local"
# Local Git Configuration Override (~/.gitconfig.local)
# Generated by make prepare

[commit]
	gpgsign = false
EOF_LOCAL
            echo -e "     ${GREEN}✅ Generated ~/.gitconfig.local with [commit] gpgsign = false.${RESET}"
        else
            echo -e "     ${YELLOW}⚠️ Skipped ~/.gitconfig.local generation.${RESET}"
            ACTION_ITEMS+=("Import GPG key ${GPG_KEY_ID} or create ~/.gitconfig.local with 'gpgsign = false'")
        fi
    fi
fi

# 5. .env check
echo -e "\n${BOLD}[5/6] Checking .env configuration...${RESET}"
ENV_FILE="$DOTFILES_DIR/.env"
ENV_EXAMPLE="$DOTFILES_DIR/.env.example"

if [ ! -f "$ENV_FILE" ]; then
    echo -e "  ${YELLOW}⚠️ .env file not found in dotfiles repository.${RESET}"
    if is_interactive && prompt_confirm "     Copy .env.example to .env now? [Y/n]"; then
        if [ -f "$ENV_EXAMPLE" ]; then
            cp "$ENV_EXAMPLE" "$ENV_FILE"
            echo -e "     ${GREEN}✅ Created .env from .env.example.${RESET}"
            echo -e "     Remember to configure your CONTEXT7_API_KEY in .env if available."
            ACTION_ITEMS+=("Add CONTEXT7_API_KEY to .env (for Context7 docs integration)")
        else
            echo -e "     ${RED}❌ .env.example not found.${RESET}"
            ACTION_ITEMS+=("Create .env manually")
        fi
    else
        echo -e "     ${YELLOW}⚠️ Skipped .env creation.${RESET}"
        ACTION_ITEMS+=("Copy .env.example to .env and configure API keys")
    fi
else
    if ! grep -q "CONTEXT7_API_KEY" "$ENV_FILE" 2>/dev/null; then
        echo -e "  ${YELLOW}⚠️ CONTEXT7_API_KEY setting is missing in .env.${RESET}"
        if is_interactive && prompt_confirm "     Append CONTEXT7_API_KEY= to .env? [Y/n]"; then
            echo "" >> "$ENV_FILE"
            echo "# Context7 Documentation MCP API Key" >> "$ENV_FILE"
            echo "CONTEXT7_API_KEY=" >> "$ENV_FILE"
            echo -e "     ${GREEN}✅ Added CONTEXT7_API_KEY to .env.${RESET}"
            ACTION_ITEMS+=("Configure CONTEXT7_API_KEY in .env")
        else
            ACTION_ITEMS+=("Add CONTEXT7_API_KEY to .env")
        fi
    else
        C7_KEY="$(grep -E '^[[:space:]]*(export[[:space:]]+)?CONTEXT7_API_KEY[[:space:]]*=' "$ENV_FILE" 2>/dev/null | tail -n 1 | sed -E 's/^[[:space:]]*(export[[:space:]]+)?CONTEXT7_API_KEY[[:space:]]*=[[:space:]]*//' | tr -d '"' | tr -d "'" | tr -d '\r' | xargs || true)"
        if [ -n "$C7_KEY" ]; then
            echo -e "  ${GREEN}✅ .env exists and CONTEXT7_API_KEY is configured.${RESET}"
        else
            echo -e "  ${YELLOW}ℹ️ .env exists, but CONTEXT7_API_KEY is empty.${RESET}"
            echo -e "     (Context7 MCP setup will be skipped if no API key is provided)"
            ACTION_ITEMS+=("Add CONTEXT7_API_KEY to .env if using Context7 MCP")
        fi
    fi
fi

# 6. GitHub SSH connectivity check
echo -e "\n${BOLD}[6/6] Checking GitHub SSH connectivity...${RESET}"
echo "  Testing SSH connection to git@github.com..."
SSH_OUT=$(ssh -T -o StrictHostKeyChecking=accept-new -o BatchMode=yes -o ConnectTimeout=5 git@github.com 2>&1 || true)
if echo "$SSH_OUT" | grep -q "successfully authenticated"; then
    GH_USER=$(echo "$SSH_OUT" | sed -n -E 's/.*Hi ([^!]+)!.*/\1/p')
    if [ -n "$GH_USER" ]; then
        echo -e "  ${GREEN}✅ GitHub SSH authentication successful (${GH_USER}).${RESET}"
    else
        echo -e "  ${GREEN}✅ GitHub SSH authentication successful.${RESET}"
    fi
else
    echo -e "  ${YELLOW}⚠️ GitHub SSH authentication failed.${RESET}"
    echo -e "     SSH response: $(echo "$SSH_OUT" | head -n 1)"
    echo -e "     Make sure your SSH key is generated and uploaded to GitHub."
    ACTION_ITEMS+=("Configure GitHub SSH keys (ssh-add or upload to https://github.com/settings/keys)")
fi

# 7. Final Summary & Transition
echo -e "\n${BOLD}=====================================================${RESET}"
echo -e "${BOLD}               PRE-FLIGHT SUMMARY                    ${RESET}"
echo -e "${BOLD}=====================================================${RESET}"

if [ ${#CRITICAL_ISSUES[@]} -gt 0 ]; then
    echo -e "${RED}❌ Critical blocker(s) detected:${RESET}"
    for issue in "${CRITICAL_ISSUES[@]}"; do
        echo -e "   • ${RED}$issue${RESET}"
    done
    echo ""
    echo "Please resolve these critical items before running 'make setup'."
    exit 1
fi

echo -e "${GREEN}🎉 All critical pre-flight checks passed!${RESET}"

if [ ${#ACTION_ITEMS[@]} -gt 0 ]; then
    echo -e "\n${YELLOW}Recommended follow-ups / reminders:${RESET}"
    for item in "${ACTION_ITEMS[@]}"; do
        echo -e "   • ${YELLOW}$item${RESET}"
    done
fi

echo ""
if is_interactive; then
    if prompt_confirm "Would you like to execute 'make setup' now? [Y/n]" "Y"; then
        echo -e "\n${BOLD}🚀 Starting 'make setup'...${RESET}\n"
        cd "$DOTFILES_DIR"
        exec make setup
    else
        echo -e "\n${GREEN}Pre-flight complete.${RESET} Run ${BOLD}make setup${RESET} whenever you are ready."
    fi
else
    echo -e "${GREEN}Pre-flight complete (non-interactive).${RESET} Run ${BOLD}make setup${RESET} to proceed with installation."
fi
